name: Plugins CI
on:
  push:
    paths:
      - 'plugins/**'
      - 'tests/**'
      - '.github/workflows/ansible-test-plugins.yml'
  pull_request:
    paths:
      - 'plugins/**'
      - 'tests/**'
      - '.github/workflows/ansible-test-plugins.yml'
  schedule:
    - cron: '0 6 * * 6'

jobs:
  sanity:
    name: "Sanity (Ansible: ${{ matrix.ansible }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible:
          - stable-2.18
          - stable-2.19
          - stable-2.20
          - stable-2.21
          - devel

    steps:
      - name: Run sanity tests
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          testing-type: sanity
          coverage: never

  units:
    runs-on: ubuntu-latest
    name: Units (Ⓐ${{ matrix.ansible }})
    strategy:
      fail-fast: true
      matrix:
        ansible:
          - stable-2.18
          - stable-2.19
          - stable-2.20
          - stable-2.21
          - devel

    steps:
      - name: Run unit tests
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          testing-type: units
          coverage: never

  integration:
    runs-on: ubuntu-latest
    name: "Integration valkey=${{ matrix.valkey_version }} ansible=${{ matrix.ansible }}"

    strategy:
      fail-fast: false
      matrix:
        ansible:
          - stable-2.18
          - stable-2.19
          - stable-2.20
          - stable-2.21
          - devel
        valkey_version:
          - "7.2.14"
          - "8.0.11"
          - "8.1.10"
          - "9.0.6"
          - "9.1.2"
        include:
        - hidden_secret: "********"
        - ansible: devel
          hidden_secret: "$REDACTED$"
    steps:
      - name: Run integration tests
        uses: ansible-community/ansible-test-gh-action@release/v1
        env:
          hidden_secret: ${{ matrix.hidden_secret }}
        with:
          ansible-core-version: ${{ matrix.ansible }}
          testing-type: integration
          coverage: never